name: stratos_s_application3
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  enhanced_enum: ^0.2.4
  url_launcher: ^6.2.2
  http: ^0.13.4
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.0
  flutter_local_notifications: ^16.3.0
  awesome_notifications: ^0.9.2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Lexend
      fonts: 
        - asset: assets/fonts/LexendRegular.ttf
          weight: 400
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoItalicRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
    - family: Crimson Pro
      fonts: 
        - asset: assets/fonts/CrimsonProRomanBold.ttf
          weight: 700

python:
  dependencies:
    mysql-connector-python: ^8.0.28
    flask: ^2.0.2